In [1]:
#step-1: We have to import the dataset to the colab note book.
import pandas as pd #pd is an instance of pandas
df=pd.read_csv('Data.csv') #read_csv is a predefine function in pandas library


In [2]:
type(df)

pandas.core.frame.DataFrame

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
#set-2:grouping the input columns and output columns
X=df.iloc[:,:3]
#slicing the input column

In [5]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [6]:
Y=df.iloc[:,3:4] #[:,-1],[:,3:5]
#slicing the output column

In [7]:
Y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [8]:
X=X.values #convert from tabular format to array format

In [9]:
X #Two-dimensional array.

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
Y=Y.values

In [11]:
Y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [12]:
#Handling missing data or values
#scenario-1:
#what we do value miss in the numerical column.
#we have to calculate mean or average.we can place the avg value in the empty place.
#missing in numerical column we have to calculate mean or average of that column.
#replace the avg or mean value in the empty place.
#scenario-2:
#missing values in unnumerical column.we have to replace in empty value with
#high repeated value.
#scenario-3:
#having missing values in usage data set.removing empty value rows from the data.

import numpy as np #np is an intance of numpy
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
#sklearn is a big library. simpleimputer assign a new values in the place of misiing values.
#simpleimputer is a calss from sklearn.which is used to new values placed in the missing values.
#simpleimputer and sklear are packages.
#simpleimputer is a class which was imported from sklearn package.
#fit can do prepare the imputer what the action do by imputer.
#fit can pass instruction to the imputer.


In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
#step-4:handling the categorical data
#when the number are collected in groups or categories.
#converting the categorical data in to numerical data.(numbers)
#onehotencoder is class which was imported from sklearn package
#onehotencoder is used to covert text to binary code (0,1)
#columntransformer is a class which was imported from sklearn package
#columntransformer is used to apply changes or transformer (updating the valuses present in the data is transformer)
#column transformer is a class which was used to apply the changes of numeric data in the place of categorical data
#Alexa-0,0,1
#encoder is a method which converts text to numeric

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=ct.fit_transform(X)



In [15]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

#encoder the output column.(OneHotEncoder is used input columns. used for output encoder)
#OneHotEncoder is apply for input column
#labelencoder is only for output column

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [17]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [18]:
#step-5:slipt the data into training and testing data.
#train_test_slipt is class which was imported from sklearn.model_selection.
#It was used for slipting the data into training and testing.
#the output based on test size.

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)


In [19]:
X_train

array([[1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [20]:
X_test

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [21]:
Y_train

array([1, 1, 0, 0, 0, 0, 0, 1])

In [22]:
Y_test

array([1, 1])

In [23]:
#step-6:feature scaling
#scaling is apply standard division to the values
#analyse the pattren

from sklearn.preprocessing import StandardScaler
sc=StandardScaler() #sc is object of standardscaler class.
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [24]:
X_train

array([[1.0, 0.0, 0.0, -0.06912225515241897, 0.4720758707393582],
       [0.0, 0.0, 1.0, -1.5328876583801172, -1.278059064684604],
       [0.0, 0.0, 1.0, 0.07725428517035086, -0.08059831939452457],
       [0.0, 0.0, 1.0, 0.19110270542139418, -0.9096096045953487],
       [1.0, 0.0, 0.0, 0.9555135271069698, 0.9326376958509272],
       [0.0, 1.0, 0.0, -1.0937580374118077, -0.7253848745507211],
       [0.0, 1.0, 0.0, 1.8337727690435888, 1.9458737110963789],
       [1.0, 0.0, 0.0, -0.3618753357979586, -0.3569354144614659]],
      dtype=object)

In [25]:
X_test

array([[0.0, 1.0, 0.0, 0.3700073658158905, 0.17526936122301404],
       [1.0, 0.0, 0.0, 1.5410196883980491, 1.5774242510071237]],
      dtype=object)

In [26]:
#machine learning
#types in machine laerning
#1.supervisioned learning
#2.unsupervisioned learnig
#3.reinforcement learning
#when we have labed data,and the model tasks are classification or peridication
#supervisioned:when we have labled data from classify the thing.
#unsupervisioned learning:unlabled data,model remembers the patterns
#and we also perform predictions in the unsupervisioned learning.
# reinforcement:model will learn from trail and error method or model will learn from failure.
#supervisioned learning algorithms:
#1.linear regression algorithm - prediction task
#2.logistic regression - classifications model (yes or no)

In [28]:
#Logistic Regression Algorithm
#when the model performce classifications task we have apply logistic regression algorithm
#Linear Regression Algorithm
#when the model performce prediction task we have to apply linear regression algurithm
#step-7:apply algorithm to the data set

from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression()
classifier.fit(X_train,Y_train)


LogisticRegression()

In [29]:
#creat a new variable

Y_pred=classifier.predict(X_test)

In [30]:
Y_pred

array([0, 0])